add-table
frontegg/opensaas pull request #70
Opened 2020-10-27 10:44 UTC by livnekes

2020-10-27 10:45 UTC, livnekes commented on frontend/src/Components/Loader/index.tsx
> +import { LoaderProps } from '@frontegg/react-core';
Create type for this

2020-10-27 10:45 UTC, livnekes commented on frontend/src/Components/Loader/index.tsx
> +    className: classNames(className, { 'fe-material-loader__centered': center }),
remove classname

2020-10-27 10:45 UTC, livnekes commented on frontend/src/Components/Loader/style.scss
> +.fe-material-loader__centered {
change class name

2020-10-27 10:46 UTC, livnekes commented on frontend/src/Components/Popup/PopupClick.tsx
> +        <Box className={classnames(classes.box, 'fe-m-popup-content')}>{content}</Box>
change class name

2020-10-27 10:46 UTC, livnekes commented on frontend/src/Components/Popup/PopupFocus.tsx
> +        <Box className={classnames(classes.box, 'fe-m-popup-content')}>{content}</Box>
change class name

2020-10-27 10:47 UTC, livnekes commented on frontend/src/Components/Popup/index.tsx
> +import { PopupProps } from '@frontegg/react-core';
replace this with types

2020-10-27 11:36 UTC, livnekes commented on frontend/src/Components/Popup/PopupHover.tsx
> +    // @ts-ignore
fix this issue

2020-10-27 11:47 UTC, livnekes commented on frontend/src/Components/Table/Table.tsx
> +import { TableProps, FeTableColumnProps, FeTableColumnOptions } from '@frontegg/react-core';
remove this

2020-11-11 10:57 UTC, frontegg-david requested changes

2020-11-11 10:57 UTC, frontegg-david commented on frontend/src/Components/Table/Table.tsx
> +  if (expandable) {
- this will not work if expandable changed
- see the last changes in FeTable

2020-11-11 10:57 UTC, frontegg-david commented on frontend/src/Pages/MainLayout/TablePage/TablePage.tsx
> +export const columns: any[] = [
why any?

2020-11-11 10:58 UTC, livnekes commented on frontend/src/Pages/MainLayout/TablePage/TablePage.tsx
> +export const columns: any[] = [
Had some trouble with this - don't know why... :(

2020-11-11 10:59 UTC, livnekes commented on frontend/src/Components/Table/Table.tsx
> +  if (expandable) {
Ok tnx

2020-12-02 15:21 UTC, livnekes commented on frontend/src/Components/Table/Table.tsx
> +  if (expandable) {
@frontegg-david I need some help with all the last changes to the Table.

2020-12-02 15:22 UTC, frontegg-david approved these changes

2020-12-03 09:32 UTC, merged